Working with DataFrames
-

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("employee.csv")
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

## Column Selection in Pandas
- df["column_name"]
- df.Column_name
- a single column will exist as a series object'

- df[data] this indexing method will take a single argument --- a `string` or a `list`
    - what if we need multiple columns

In [33]:
# acessing columns in the dataframe
# access columns by --- Name
df['Name']
df.Name # only one column


columns = ["Name","Salary",	"Experience"]
df[columns]

# subset of dataframe
df_salary = df[["Salary",	"Experience"]]
display(df_salary)

#df["Name","Salary"] # will not work

   Salary  Experience
0   75000           3
1   65000           5
2   80000           7
3   60000           2
4   70000           4

In [34]:
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

### Selection using the location or Labels

integer Location --- .iloc[]
- df.iloc[row index] 3 access rows
- df.iloc[row_index_slice] # [start: end : stepsize]

INDEXING ----
- df.iloc[row_slice, column_slice]
-

In [35]:
df.iloc[0]
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [36]:
df.iloc[0] # first row as a series object

df.iloc[-1] # last row

df.iloc[1:3] # rows from 1 upto 3

df.iloc[1:4:2] # in steps of 2

# ---- indexing works

df.iloc[:4, 1:3] #first 4 rows, 

df.iloc[[0,2,3], [0,2,3]] # you can access the rows, columns by number, but
# if out of index, error will be thrown
# errors are not thrown if you are accessing using slices

      Name  Salary  Experience
0    Alice   75000           3
2  Charlie   80000           7
3    Diana   60000           2

In [37]:
# i want the data of the last two entries, for department and experience
df.iloc[-2:,[1,3]]

  Department  Experience
3         HR           2
4  Marketing           4

## Label - .loc[]

- focuses on labels
- df.loc[0:3] # targets the names of these rows
- Which are the indexes

In [38]:
# 
ind = ['a','b','c','d','e']
df = pd.read_csv("employee.csv")
df['index'] = ind

df = df.set_index('index')
display(df)
# -----
df.index = ['a','b','c','d','e']
display(df)

          Name   Department  Salary  Experience
index
a        Alice  Engineering   75000           3
b          Bob    Marketing   65000           5
c      Charlie  Engineering   80000           7
d        Diana           HR   60000           2
e          Eve    Marketing   70000           4

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [39]:
df.loc[0] # row
df.loc[0:3] # slice of rows

# df.loc[0:3, 0:3] # throws an error

df.loc[0:3, ['Department', 'Experience']]

KeyError: 0

In [ ]:
df.loc['a':'d', 'Department':'Experience':2]

    Department  Experience
a  Engineering           3
b    Marketing           5
c  Engineering           7
d           HR           2

In [ ]:
df = pd.read_csv("employee.csv")

df.index = ("a","b","c","d","e")
 
df

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [ ]:
df.index
df.columns

Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')

In [ ]:
df.iloc[[0,2,3], [0,2,4]]   # you can access the rows, columns by number, but 
# it out of index, error will be thrown

In [ ]:
# EXCERCISE
# 
# i want the data of the last two entries, for department and experience

df.iloc[-2,[1,3]]

Department    HR
Experience     2
Name: d, dtype: object

- Label - ,loc[]
- focuses on labels
- df.loc[0:3]   # targets the names of these rows
- which are the indexes
-

In [ ]:

df.loc[0]   # row
df.loc[0:3] # slice of rows

df.loc[0:3, 0:3]

In [ ]:
#
ind = ['a', 'b', 'c', 'd', 'e']
df = pd.read_csv("employee.csv")
df['index'] = ind

df.set_index('index')
display(df)

In [ ]:
# Optional_Luqman

df = pd.read_csv("employee.csv")
df.index = ("a","b","c","d","e")
 
df

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

Adding and Modifiying Columns

In [ ]:
df.iloc[0:3, 0:2]

      Name   Department
a    Alice  Engineering
b      Bob    Marketing
c  Charlie  Engineering

In [ ]:
# adding a column
# access a column that does does not exist
df['email'] = {}
df

# df['email'] = []
df

      Name   Department  Salary  Experience              email
a    Alice  Engineering   75000           3     alice@gmailcom
b      Bob    Marketing   65000           5      bob@gmail.com
c  Charlie  Engineering   80000           7  charlie@gmail.com
d    Diana           HR   60000           2    diana@gmail.com
e      Eve    Marketing   70000           4      eve@gmail.com

In [ ]:
df['email'] = ['alice@gmailcom', 'bob@gmail.com', 'charlie@gmail.com', 'diana@gmail.com', 'eve@gmail.com']
df

      Name   Department  Salary  Experience              email
a    Alice  Engineering   75000           3     alice@gmailcom
b      Bob    Marketing   65000           5      bob@gmail.com
c  Charlie  Engineering   80000           7  charlie@gmail.com
d    Diana           HR   60000           2    diana@gmail.com
e      Eve    Marketing   70000           4      eve@gmail.com

In [42]:
# modify
df['Department']['d'] = 'Crime Analytics'
df

C:\Users\user\AppData\Local\Temp\ipykernel_24732\4083700284.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['Department']['d'] = 'Crime Analytics'

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [53]:
list(df['Department'])

df['Department'] = ['Engineering', 'Marketing', 'Physics', 'HR', 'Marketing']

# use modify all elements in one go
df.Salary = df.Salary/1000  # Scaling operation
# took the column and scled it down

df.Experience = df.Experience +1

In [52]:
# modifying a value
# df['Department']['d'] = 'Crime Analytics'


df.loc['d','Department'] = 'Crime Analytics'
df

,Name,Department,Salary,Experience,"(Department, d)","(d, Department)"
a,Alice,Engineering,0.000075,6,Crime Analytics,Crime Analytics
b,Bob,Marketing,0.000065,8,Crime Analytics,Crime Analytics
c,Charlie,Physics,0.000080,10,Crime Analytics,Crime Analytics
d,Diana,Crime Analytics,0.000060,5,Crime Analytics,Crime Analytics
e,Eve,Marketing,0.000070,7,Crime Analytics,Crime Analytics

### EDA (Exploratory Data Analaysis) with Pandas
- some methods that we can run on dataframes
- df.head()     - give you the first 5 elements
    - an arguments of  will give you first  emlements
- df.tail()     - 
- df.sample()

- Basic attributes of a dataframe
- df.shape
- df.size       - how many elements there are
- df.ndim       - will tell you the number of axes there are in the df ---- generally just 2
- `df.dtypes`   - 


- df.info()
- df.describe()

In [59]:
df.head(10)
df.tail()
df.sample()

df.shape
df.size
df.dtypes


df.info()
df.describe()

<class 'pandas.DataFrame'>
Index: 5 entries, a to e
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             5 non-null      str
 1   Department       5 non-null      str
 2   Salary           5 non-null      float64
 3   Experience       5 non-null      int64
 4   (Department, d)  5 non-null      str
 5   (d, Department)  5 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 452.0+ bytes

             Salary  Experience
count  5.000000e+00    5.000000
mean   7.000000e-08    8.200000
std    7.905694e-09    1.923538
min    6.000000e-08    6.000000
25%    6.500000e-08    7.000000
50%    7.000000e-08    8.000000
75%    7.500000e-08    9.000000
max    8.000000e-08   11.000000

Exercise:
- Please go to Kaggle
- Download this dataset: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially the EDA that we learnt about in today's class on it

### Filtering

### Aggregation

### Grouping