## EDA (Exploratory Data Analysis) with Pandas

- 1st step in data analysis & ML too
- 3 parts -
    1. Data Cleaning - identify & remove missing values
    2. Data Summarisation check the dataset- 
    3. Data Visualisation - 
-  one of 

- Some methods that we can run on dataframes
- Basic Inspection methods: (Data Summarization)
    - `df.head()` - give you the first 5 elements
        - an argument of 10 will give you first 10 elements
    - df.tail() - last 5 but argument can change the number
    - `df.sample()` - one random entry from the dataset
        - an argument can change that number too 
        - we use this to check how our datasets look like inside
- Basic attributes of a dataframe:
    - `df.shape` - tells you the shape of the df --- how many elements along how many axes
    - df.size - how many elements there are
    - df.ndim - will tell you the number of axes there are in the df --- generally just 2
    - `df.dtypes` - will tell you the data type of each column



- Methods for Statistical information as well:
    - `df.info()` - general information about the df
        - how many records, how many columns, what is the data type of those columns
        - also gives an idea of if there are any missing values in data
    - `df.describe()` - gives us the statistical measurements of the columns like count, mean, min, max, std, percentiles 
-

In [4]:
#df.head(10)
#df.tail()
#df.sample(4)

#df.shape
#df.size 
#df.dtypes

#df.info()

#df.describe()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
99,NaN,Quarter-final,QF7,QF8,NRG Stadium,Houston,USA,2026-07-11,TBD,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,Semi-final,SF1,SF2,AT&T Stadium,Arlington,USA,2026-07-14,TBD,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,Semi-final,SF3,SF4,MetLife Stadium,East Rutherford,USA,2026-07-15,TBD,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,3rd Place Match,3rd Place,3rd Place,Hard Rock Stadium,Miami,USA,2026-07-18,TBD,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,Final,Finalist 1,Finalist 2,MetLife Stadium,East Rutherford,USA,2026-07-19,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd
df = pd.read_csv('wc_2026.csv')
display(df)

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,NaN,Quarter-final,QF7,QF8,NRG Stadium,Houston,USA,2026-07-11,TBD,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,Semi-final,SF1,SF2,AT&T Stadium,Arlington,USA,2026-07-14,TBD,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,Semi-final,SF3,SF4,MetLife Stadium,East Rutherford,USA,2026-07-15,TBD,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,3rd Place Match,3rd Place,3rd Place,Hard Rock Stadium,Miami,USA,2026-07-18,TBD,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,Final,Finalist 1,Finalist 2,MetLife Stadium,East Rutherford,USA,2026-07-19,TBD,NaN,NaN,NaN,NaN,NaN,NaN

### Filtering
- filter rows & columns
- uses boolean indexing
- keep only the rows you care about

- df[condition] # or mask

In [5]:
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [10]:
import pandas as pd
# show me the matches played in Canada
# mask = df["Country"] == "Canada"
# df[mask]
df[df["country"] == "Canada"]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Q2 : give me data for the matches in which team1_fifa_rank was <=10
df[df["team1_fifa_rank"] <= 10]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui
14,C,Group Stage,Brazil,Scotland,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CONMEBOL,6.0,Dorival Júnior,UEFA,47.0,Steve Clarke
15,C,Group Stage,Morocco,Haiti,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
17,C,Group Stage,Morocco,Haiti,Gillette Stadium,Foxborough,USA,2026-06-24,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
24,E,Group Stage,Germany,Curaçao,NRG Stadium,Houston,USA,2026-06-14,13:00 ET,UEFA,10.0,Julian Nagelsmann,CONCACAF,81.0,Dick Advocaat
26,E,Group Stage,Germany,Ivory Coast,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,10.0,Julian Nagelsmann,CAF,33.0,Emerse Faé
30,F,Group Stage,Netherlands,Japan,AT&T Stadium,Arlington,USA,2026-06-14,16:00 ET,UEFA,7.0,Ronald Koeman,AFC,18.0,Hajime Moriyasu
32,F,Group Stage,Netherlands,Sweden,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,7.0,Ronald Koeman,UEFA,39.0,Jon Dahl Tomasson
36,G,Group Stage,Belgium,Egypt,Lumen Field,Seattle,USA,2026-06-15,15:00 ET,UEFA,9.0,Domenico Tedesco,CAF,29.0,Hossam El-Badry
38,G,Group Stage,Belgium,Iran,SoFi Stadium,Inglewood,USA,2026-06-21,18:00 ET,UEFA,9.0,Domenico Tedesco,AFC,21.0,Amir Ghalenoei
42,H,Group Stage,Spain,Cape Verde,Mercedes-Benz Stadium,Atlanta,USA,2026-06-15,12:00 ET,UEFA,2.0,Luis de la Fuente,CAF,70.0,Pedro Brito
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
54,J,Group Stage,Argentina,Algeria,Arrowhead Stadium,Kansas City,USA,2026-06-16,21:00 ET,CONMEBOL,3.0,Lionel Scaloni,CAF,36.0,Vladimir Petkovic
56,J,Group Stage,Argentina,Austria,AT&T Stadium,Arlington,USA,2026-06-22,13:00 ET,CONMEBOL,3.0,Lionel Scaloni,UEFA,23.0,Ralf Rangnick
60,K,Group Stage,Portugal,DR Congo,NRG Stadium,Houston,USA,2026-06-17,13:00 ET,UEFA,5.0,Roberto Martínez,CAF,51.0,Sébastien Desabre
62,K,Group Stage,Portugal,Uzbekistan,Arrowhead Stadium,Kansas City,USA,2026-06-23,13:00 ET,UEFA,5.0,Roberto Martínez,AFC,62.0,Srecko Katanec
66,L,Group Stage,England,Croatia,AT&T Stadium,Arlington,USA,2026-06-17,15:00 ET,UEFA,4.0,Thomas Tuchel,UEFA,11.0,Zlatko Dalić
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo

In [16]:
#Q3 : give me data for the matches in which both team were <10 fifa rank

df[(df["team1_fifa_rank"] < 10) & (df["team2_fifa_rank"] < 10)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui

In [13]:
# Q4 : Find all matches where Mexico is playing
# specially as team1, AND the venue is "Estadio Azteca"

df[(df["team1"] == "Mexico") & (df["venue"] == "Estadio Azteca")]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos

In [14]:
# Question 5: Write the code to find all matches played in either "Toronto" OR "Vancouver"
df[(df["city"] == "Toronto") | (df["city"] == "Vancouver")].shape

(9, 15)

In [26]:
# Question 6: Write a single line of pandas code to find matches where:
# team1 is ranked strictly better (lower number) than team2 AND
# The match is either in Mexico OR Canada
df[(df["team1_fifa_rank"] < df["team2_fifa_rank"]) & ((df["country"] == "Mexico") | (df["country"] == "Canada"))]

# team1_better = df['team1_fifa_rank'] < df['team2_fifa_rank']
# match_mex_can = (df['country'] == "Mexico") | (df['country'] == "Canada")
# df[team1_better & match_mex_can]

#df[(
    #(df["team1_fifa_rank"] < df["team2_fifa_rank"]) &
   # (
   #     (df["country"] == "Mexico") |
    #    (df["country"] == "Canada")))]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
31,F,Group Stage,Sweden,Tunisia,Estadio BBVA,Monterrey,Mexico,2026-06-14,20:00 ET,UEFA,39.0,Jon Dahl Tomasson,CAF,40.0,Faouzi Benzarti
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen

In [27]:
import pandas as pd
df = pd.read_csv('wc_2026.csv')
# display(df)

# Q7 : 

mask = df[(df["team1_fifa_rank"] < df["team2_fifa_rank"]) & ((df["country"] == "Mexico") | (df["country"] == "Canada"))]
mask
# mask = True Rows
# using .loc to target
df.loc[mask, ["team1", "team2", "country"]]

# sorting data in data frames
df2.sort_values(by = "team1", ascending = False)

ValueError: Cannot index with multidimensional key

### sorting Data in DFs

- highest numbers or

### Aggregration
- sometimes we need to get aggregate values of columns
- methods : sum(), min(), max(), mean()

- AXIS --- 0 >>>> of columns wise
- AXIS --- 1 >>>> of rows wise

# use of axis argument 3 places:
- "AGGREGATES" numpy 2D array & DataFrames
    - axis = 0 ---> columns wise aggregates
    - axis = 1 ---> row wise aggregates

- "DROP" a column or row in dataframes
    - axis = 0 ---> drop ROW (melintang)
    - axis = 1 ---> drop COLUMN (menegak)


- Series.agg(['mean','max','min', 'count', 'sum', 'std', 'var','prod'])

In [ ]:
# Drop all missing values
# Row with a single NaN value --- is dropped
df.dropna(inplace = True) # Original will be affected
 
# df.info()
 
# give me an aggregate for the two columns

df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 0)

# give me an aggregate for the all the 72 rows
 
df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 1)

0     15.0
1     25.0
2     15.0
3     41.0
4     15.0
      ...
67    53.0
68     4.0
69    11.0
70     4.0
71    11.0
Length: 72, dtype: float64

In [41]:
df["team2_fifa_rank"].agg(["mean","min","max","count","std","var"])

mean      37.916667
min        1.000000
max       95.000000
count     72.000000
std       23.836739
var      568.190141
Name: team2_fifa_rank, dtype: float64

In [27]:
import pandas as pd 
# df = pd.DataFrame()
df_emp = pd.read_csv("employees.csv")
df_emp

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [ ]:

df_emp[['Salary','Experience']].mean(axis = 0) # axis = 0  Column wise

df_emp[['Salary','Experience']].mean(axis = 1) # ROW WISE aggregates

0    37501.5
1    32502.5
2    40003.5
3    30001.0
4    35002.0
dtype: float64

In [ ]:
import pandas as pd
df = pd.read_csv('wc_2026.csv')

df.team1_fifa_rank.min()

#df[["team1_fifa_rank", "team2_fifa_rank"]].mean()
#df[["team1_fifa_rank", "team2_fifa_rank"]].max()
#df[["team1_fifa_rank", "team2_fifa_rank"]].min()
#df[["team1_fifa_rank", "team2_fifa_rank"]].median()
df[["team1_fifa_rank", "team2_fifa_rank"]].mean(axis = 0) # cloumn wise
#df[["team1_fifa_rank", "team2_fifa_rank"]].mean(axis = 1) # cloumn wise
#df[["team1_fifa_rank", "team2_fifa_rank"]].mode()
#df[["team1_fifa_rank", "team2_fifa_rank"]].mode().iloc[0]

team1_fifa_rank    30.208333
team2_fifa_rank    37.916667
dtype: float64

In [38]:
df[(df["team1_fifa_rank"]==1) | (df["team2_fifa_rank"]==1)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
52,I,Group Stage,Norway,France,MetLife Stadium,East Rutherford,USA,2026-06-26,15:00 ET,UEFA,44.0,Ståle Solbakken,UEFA,1.0,Didier Deschamps

## Grouping
- group the data by some category
- "df.groupbt("category)["col1,col2,col2,...].aggregation()"

- using df.groupy('category').count() - will give you all the columns for each row
- using df.groupy('category').szie() - will give you only the categories and their count

In [42]:
df_emp.head()

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [53]:
print(df_emp.groupby("Department"))

print(df_emp.groupby("Department").head)

df_emp.groupby("Department")["Salary"].count()

df_emp.groupby("Department")[["Salary", "Experience"]].count()

df_emp.groupby("Department")[["Name", "Salary", "Experience"]].count()

<pandas.api.typing.DataFrameGroupBy object at 0x00000248A14D1B70>
<bound method GroupBy.head of <pandas.api.typing.DataFrameGroupBy object at 0x00000248A14D1B70>>

             Name  Salary  Experience
Department
Engineering     2       2           2
HR              1       1           1
Marketing       2       2           2

In [ ]:
df
# how many appearances has mexico made
df.groupby("country").count()
# same below 
df.groupby("country").size()

country
Canada     7
Mexico    12
USA       53
dtype: int64

## combine DataFrames
- two dataframe & want to combine together


JOINS -

- are used to combine two tables
- this happens along a KEY column ---> PRIMARY KEY --- we cover this in SQL

In [62]:
# Student info
students = {
    "StudentID": [1, 2, 3],
    "Student": ["Aman", "Sara", "John"]
}
df_students = pd.DataFrame(students)
display(df_students)

# Marks info
marks = {
    "StudentID": [2, 3, 4],
    "Math": [85, 90, 78],
    "English": [88, 92, 80]
}
df_marks = pd.DataFrame(marks)
display(df_marks)

   StudentID Student
0          1    Aman
1          2    Sara
2          3    John

   StudentID  Math  English
0          2    85       88
1          3    90       92
2          4    78       80

In [63]:
# Merge
# INNER JOIN 
df_merged_IJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'inner')
# `on` will be a column that is inside both tables, and each row in this column, should be unique 

# All ID elements should match

df_merged_IJ

   StudentID Student  Math  English
0          2    Sara    85       88
1          3    John    90       92

In [64]:

# LEFT JOIN
df_merged_LJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'left')
df_merged_LJ

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara  85.0     88.0
2          3    John  90.0     92.0

In [65]:

# RIGHT JOIN
df_merged_RJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'right')
df_merged_RJ

   StudentID Student  Math  English
0          2    Sara    85       88
1          3    John    90       92
2          4     NaN    78       80

In [66]:

# OUTER JOIN
df_merged_FJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'outer')
df_merged_FJ

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara  85.0     88.0
2          3    John  90.0     92.0
3          4     NaN  78.0     80.0

In [67]:

# CONCAT
# Put one table next to the other or On top of the other

pd.concat([df_students,df_marks], ignore_index = False)

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara   NaN      NaN
2          3    John   NaN      NaN
0          2     NaN  85.0     88.0
1          3     NaN  90.0     92.0
2          4     NaN  78.0     80.0