Data Cleaning

- First you check for inconsistencies in data
    - Missing Values
    - Duplicates 
    - Errors
    - Outliers 

- Removal or replacement
- 
- Every dataset has its identity:
    - Data Distribution
        - how is the data spead about - what is the std deviation, variance
    - Central Tendencies
        - where the centre of the data is located
        - mean median mode --- represent the centre of the data
    - Data Transformations : Feature scaling is one of the things we do here
        - Normalisation - adjust values to a common scale
            - Min-Max Scaling [0,1] or [-1,0]
            - entire data is squished between 0 to 1
        - Standardisation - convert data to a standard form for a common scale
            - mean 0 & std deviation 1
            - 


- Feature scaling - take a feature / column & you transform it entirely

In [4]:
# Feature scaling eg

import numpy as np
salary = np.array ([1000000,2000000,3000000,4000000,5000000,6000000])
salary_in1m = salary /1_000_000
salary_in1m
# scaling - if you are increasing o

array([1., 2., 3., 4., 5., 6.])

In [21]:
import numpy as np

# Sample dataset of e-commerce transactions
# Create a dictionary of multiple data items
data = [
    {"ID": 1001, "Name": "Alice Smith",  "Email": "alice@example.com",        "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15",   "Delivery Status": True},
    {"ID": 1002, "Name": "Bob Jones",    "Email": None,                       "Product": "Headphones", "Quantity": 2,    "Price": 150.00,  "Purchase Date": "2024-09-16",   "Delivery Status": True},
    {"ID": 1003, "Name": "Charlie John", "Email": "charlie#example.com",      "Product": "Smartphone", "Quantity": 1,    "Price": 800.00,  "Purchase Date": "16/09/2024",   "Delivery Status": True},
    {"ID": 1004, "Name": "David Lee",    "Email": "david.lee@example.com",    "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-17",   "Delivery Status": False},
    {"ID": 1005, "Name": "Eve Martinez", "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 3,    "Price": None,    "Purchase Date": "17th Sep 2024","Delivery Status": True},
    {"ID": 1006, "Name": "Frank Wright", "Email": None,                       "Product": "Tablet",     "Quantity": None, "Price": 600.00,  "Purchase Date": "2024-09-18",   "Delivery Status": False},
    {"ID": 1007, "Name": "Grace Lee",    "Email": "grace.lee@example.com",    "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-19",   "Delivery Status": True},
    {"ID": 1008, "Name": "Hank Brown",   "Email": "hank.brown@example.com",   "Product": "Monitor",    "Quantity": 2,    "Price": 300.00,  "Purchase Date": "09/19/2024",   "Delivery Status": True},
    {"ID": 1009, "Name": "Ivy Thompson", "Email": None,                       "Product": "Keyboard",   "Quantity": 2,    "Price": 100.00,  "Purchase Date": "2024/09/20",   "Delivery Status": False},
    {"ID": 1010, "Name": "Jack Davis",   "Email": "jack@example.com",         "Product": "Mouse",      "Quantity": 5,    "Price": 50.00,   "Purchase Date": "2024-09-21",   "Delivery Status": True},
    {"ID": 1011, "Name": "Alice Smith",  "Email": "alice@example.com",        "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15",   "Delivery Status": True},  # Duplicate entry
    {"ID": 1012, "Name": "Kurt Evans",   "Email": "kurt.evans@example.com",   "Product": "Smartwatch", "Quantity": -1,   "Price": 200.00,  "Purchase Date": "2024-09-22",   "Delivery Status": True},  # Outlier quantity
    {"ID": 1013, "Name": "Liam Adams",   "Email": "liam.adams@example.com",   "Product": "Headphones", "Quantity": 2,    "Price": 150.00,  "Purchase Date": "2024-09-23",   "Delivery Status": False},
    {"ID": 1014, "Name": "Mia Clark",    "Email": "mia.clark@example.com",    "Product": None,         "Quantity": 1,    "Price": 0,       "Purchase Date": "2024-09-24",   "Delivery Status": True},  # Price anomaly
    {"ID": 1015, "Name": "Nina Turner",  "Email": None,                       "Product": "Tablet",     "Quantity": 1,    "Price": 600.00,  "Purchase Date": "24-09-2024",   "Delivery Status": True},
    {"ID": 1016, "Name": "Oscar Harris", "Email": "oscar.harris@example.com", "Product": "Laptop",     "Quantity": 2,    "Price": 1200.00, "Purchase Date": "2024-09-25",   "Delivery Status": True},
    {"ID": 1017, "Name": "Paul Young",   "Email": "paulyoung",                "Product": "Monitor",    "Quantity": 2,    "Price": 300.00,  "Purchase Date": "09/25/2024",   "Delivery Status": True},
    {"ID": 1018, "Name": "Quinn Lopez",  "Email": None,                       "Product": "Smartphone", "Quantity": 1,    "Price": 800.00,  "Purchase Date": "2024-09-26",   "Delivery Status": False},
    {"ID": 1019, "Name": "Rachel Scott", "Email": "rachel.scott@example.com", "Product": "Keyboard",   "Quantity": 2,    "Price": 100.00,  "Purchase Date": "2024-09-27",   "Delivery Status": True},
    {"ID": 1020, "Name": "Steve King",   "Email": "steve.king@example.com",   "Product": "Mouse",      "Quantity": None, "Price": 50.00,   "Purchase Date": "2024-09-28",   "Delivery Status": True},
]

# Displaying the dataset
import pandas as pd

# Convert the list of dictionaries to a DataFrame for easier visualization and manipulation
df = pd.DataFrame(data)
df.head()

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie John,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True

In [25]:
# data inspection
df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               20 non-null     int64
 1   Name             20 non-null     str
 2   Email            15 non-null     str
 3   Product          19 non-null     str
 4   Quantity         18 non-null     float64
 5   Price            19 non-null     float64
 6   Purchase Date    20 non-null     str
 7   Delivery Status  20 non-null     bool
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 1.2 KB

               ID   Quantity        Price
count    20.00000  18.000000    19.000000
mean   1010.50000   1.611111   536.842105
std       5.91608   1.195033   472.241142
min    1001.00000  -1.000000     0.000000
25%    1005.75000   1.000000   125.000000
50%    1010.50000   1.500000   300.000000
75%    1015.25000   2.000000  1000.000000
max    1020.00000   5.000000  1200.000000

In [3]:
# missing value check

df.isna() # summary of missing info
df.isnull().sum() # number of missing values

df.duplicated() #if duplicated it show True
df.duplicated().sum()

np.int64(0)

## Handling Missing Values
- deletion (removal of these missing values)
    - Listwise:
        - rows where any data is missing
    -Pairwise:
        - remove specific fields with values, keep the rest
- Imputatiom (filling in the missing values)
    - estimate/calculate/predict the values that should have been there
    - should not affect the identity of the data set too drastically
    - distribution, the central tendencies should remain allmost intact
    - Types:
        - mean.median/mode imputation - put these values in missing places 
        - predective imputation - using ML we predict 
        - forward/backward fill -

In [26]:
#listwise
df_listwise = df.dropna()
df_listwise.isna().sum()

df_listwise.info() # only 12 entries remaining

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 18
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               12 non-null     int64
 1   Name             12 non-null     str
 2   Email            12 non-null     str
 3   Product          12 non-null     str
 4   Quantity         12 non-null     float64
 5   Price            12 non-null     float64
 6   Purchase Date    12 non-null     str
 7   Delivery Status  12 non-null     bool
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 780.0 bytes

In [27]:
#pairwise
df.isnull().sum()

#df_pairwise = df.dropna(subset = "Email")
df_pairwise = df.dropna(subset=['Email','Product','Quantity','Price'])
#df_pairwise.isnull().sum()
#df_pairwise.info()

#df1 = pd.DataFrame(df_pairwise)
#df1

In [32]:
#pairwise
df.isnull().sum()

df_pairwise = df.dropna(subset=['Email','Product','Quantity','Price'])
df_pairwise.isnull().sum()

df_pairwise.info()

#df1 = pd.DataFrame(df_pairwise)
#df1

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 18
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               12 non-null     int64
 1   Name             12 non-null     str
 2   Email            12 non-null     str
 3   Product          12 non-null     str
 4   Quantity         12 non-null     float64
 5   Price            12 non-null     float64
 6   Purchase Date    12 non-null     str
 7   Delivery Status  12 non-null     bool
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 780.0 bytes

In [6]:
### Imputation

df.isna().sum()

#mean_qnty = df.Quantity.mean()
#mean_qnty

#df.Quantity = df["Quantity"].fillna(mean_qnty)
#df

ID                 0
Name               0
Email              5
Product            1
Quantity           2
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

In [7]:
### Imputation

df2 = df.copy()

df2.isna().sum()

df2 = df2.dropna(subset = ["Product"]).reset

#mean_qnty = df2.Quantity.mean()
#mean_qnty

#df2.Quantity = df2["Quantity"].fillna(mean_qnty)
mode_qnty = df["Quantity"].mode()[0]

mode_qnty
#df2.Quantity = df2["Quantity"].fillna(mode_qnty)
df2

# remove the negative sign from quantity because it is an error
# df.loc[df["Quantity"] < 0, "Quantity"] = 0
#df["Quantity"] = df["Quantity"].abs()
import math
df2Quantity = ((df2["Quantity"]) **2 )**0.5
df2Quantity

# group prodcuts & tell me 
df_product_mode = df2.groupby("Product")["Quantity"].agg(lambda x :x.mode()[0])

AttributeError: 'DataFrame' object has no attribute 'reset'

In [8]:
# lets impute quantity
#df_product_mode["Headphones"]
#df2["Quantity"] = df.["Quantity"].fillna(
    #df.groupby("Product")["Quantity"].transform((lambda x :x.mode()[0]))
#)



df2["Quantity"] = df2["Quantity"].fillna(
    df2.groupby("Product")["Quantity"].transform(lambda x: x.mode()[0])
)

df2["Quantity"]

0     1.0
1     2.0
2     1.0
3     1.0
4     3.0
5     1.0
6     1.0
7     2.0
8     2.0
9     5.0
10    1.0
11   -1.0
12    2.0
13    1.0
14    1.0
15    2.0
16    2.0
17    1.0
18    2.0
19    5.0
Name: Quantity, dtype: float64

In [9]:
# group products & tell me the most common amount of quantity customers order

most_common_quantity = df["Quantity"].mode()[0]
most_common_quantity

product_quantity = df.groupby("Product")["Quantity"].sum()

print("\nTotal quantity sold by product:")
print(product_quantity.sort_values(ascending=False))


# Most common quantity ordered
most_common_quantity = df["Quantity"].mode()[0]

print("\nMost common quantity customers order:")
print(most_common_quantity)

Total quantity sold by product:
Product
Laptop        6.0
Mouse         5.0
Keyboard      4.0
Headphones    4.0
Monitor       4.0
Smartphone    2.0
Smartwatch    2.0
Tablet        1.0
Name: Quantity, dtype: float64

Most common quantity customers order:
1.0

In [10]:
df.groupby("Product")["Quantity"].sum()
df.groupby("Product")["Quantity"].count()
df.groupby("Product")["Quantity"].mean()
df.groupby("Product")["Quantity"].agg(
    lambda x : x.mode()[0]
)

Product
Headphones    2.0
Keyboard      2.0
Laptop        1.0
Monitor       2.0
Mouse         5.0
Smartphone    1.0
Smartwatch   -1.0
Tablet        1.0
Name: Quantity, dtype: float64

In [17]:
# its not logical to impute an email column
# this pattern will most likely not be true for all customers
# imputing emails based on first name & last name
# email = "Firstname" + "Lastname" + example.com

#split_name = df2["Name"].str.split(" ", n=1, expand=True)

#df2["Email"] = df2["Email"].fillna(
    #split_name[0].str.lower() +
    #split_name[1].fillna("").str.lower() +
    #"@example.com"
#)

# df2['New_email'] = df['Name'] + '@gmail.com'

#df2["Email"] = df2["Name"].fillna("") + "@example.com"

# df2["Email"] = (df2["Name"].fillna("").str.replace(" ", "").str.lower()+ "@example.com")

df2["Email"] = (df2["Name"].str.replace(" ", "").str.lower()+ "@example.com")

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alicesmith@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,bobjones@example.com,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie John,charliejohn@example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,davidlee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,evemartinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,frankwright@example.com,Tablet,1.0,600.0,2024-09-18,False
6,1007,Grace Lee,gracelee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hankbrown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,ivythompson@example.com,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jackdavis@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alicesmith@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurtevans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liamadams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,miaclark@example.com,NaN,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,ninaturner@example.com,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscarharris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung@example.com,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,quinnlopez@example.com,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachelscott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steveking@example.com,Mouse,5.0,50.0,2024-09-28,True

In [20]:
# df2["Price"] = df2["Price"].fillna(df2["Price"].mean()).round(0).astype(int)
# df2["Price"] = df2["Price"].fillna(df2["Price"].mean()).round(0)

df2["Price"] = df2["Price"].fillna(df2.groupby("Product")["Price"].transform("mean")).round(0)
df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alicesmith@example.com,Laptop,1.0,1200,2024-09-15,True
1,1002,Bob Jones,bobjones@example.com,Headphones,2.0,150,2024-09-16,True
2,1003,Charlie John,charliejohn@example.com,Smartphone,1.0,800,16/09/2024,True
3,1004,David Lee,davidlee@example.com,Laptop,1.0,1200,2024-09-17,False
4,1005,Eve Martinez,evemartinez@example.com,Smartwatch,3.0,537,17th Sep 2024,True
5,1006,Frank Wright,frankwright@example.com,Tablet,1.0,600,2024-09-18,False
6,1007,Grace Lee,gracelee@example.com,Laptop,1.0,1200,2024-09-19,True
7,1008,Hank Brown,hankbrown@example.com,Monitor,2.0,300,09/19/2024,True
8,1009,Ivy Thompson,ivythompson@example.com,Keyboard,2.0,100,2024/09/20,False
9,1010,Jack Davis,jackdavis@example.com,Mouse,5.0,50,2024-09-21,True
10,1011,Alice Smith,alicesmith@example.com,Laptop,1.0,1200,2024-09-15,True
11,1012,Kurt Evans,kurtevans@example.com,Smartwatch,-1.0,200,2024-09-22,True
12,1013,Liam Adams,liamadams@example.com,Headphones,2.0,150,2024-09-23,False
13,1014,Mia Clark,miaclark@example.com,NaN,1.0,0,2024-09-24,True
14,1015,Nina Turner,ninaturner@example.com,Tablet,1.0,600,24-09-2024,True
15,1016,Oscar Harris,oscarharris@example.com,Laptop,2.0,1200,2024-09-25,True
16,1017,Paul Young,paulyoung@example.com,Monitor,2.0,300,09/25/2024,True
17,1018,Quinn Lopez,quinnlopez@example.com,Smartphone,1.0,800,2024-09-26,False
18,1019,Rachel Scott,rachelscott@example.com,Keyboard,2.0,100,2024-09-27,True
19,1020,Steve King,steveking@example.com,Mouse,5.0,50,2024-09-28,True