Woroking with DataFrames

In [2]:
import pandas as pd

In [24]:
import pandas as pd 
# df = pd.DataFrame()
df = pd.read_csv("employees.csv")
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

## columns selection in Pandas
-

In [ ]:
# acessing columns in th dataFrame
# access columns by name

df["Name"]
df.Name # only one column

columns = ["Name", "Salary", "Experience"]
df[columns]

df[["Name", "Salary", "Experience"]]

#subset of dataframe

      Name  Salary  Experience
0    Alice   75000           3
1      Bob   65000           5
2  Charlie   80000           7
3    Diana   60000           2
4      Eve   70000           4

# Selection using the location or labels
    - Location -- .iloc[]
    - df.iloc[row index] #access  :stepsize

    - df.iloc[row_index_slice] # start:end
    - df.iloc[row_slice,column]

In [19]:
df.iloc[0] #first row as a series

df.iloc[1:4] #rows from 1 up to 3

df.iloc[1:4:2] #in the step 2

df.iloc[-1] # last row
# display(df)

# --- indexing work as well
df.iloc[:4,1:3] #first 4 rows

# df.iloc[[0,2,3],[0,2,4]] # you can access the rows, columns

    Department  Salary
0  Engineering   75000
1    Marketing   65000
2  Engineering   80000
3           HR   60000

In [16]:
# i want the data of the last two entries for department & experince

print(df.iloc[-2:,[1,3]])

  Department  Experience
3         HR           2
4  Marketing           4

In [10]:
df = pd.read_csv("employees.csv", index_col="Name")
display(df)

          Department  Salary  Experience
Name
Alice    Engineering   75000           3
Bob        Marketing   65000           5
Charlie  Engineering   80000           7
Diana             HR   60000           2
Eve        Marketing   70000           4

In [19]:
ind = ["a","b","c","d","e"]
df = pd.read_csv("employees.csv")
df["index"] = ind

df = df.set_index("index")
display(df)

df.index = ["a","b","c","d","e"]
display(df)

          Name   Department  Salary  Experience
index
a        Alice  Engineering   75000           3
b          Bob    Marketing   65000           5
c      Charlie  Engineering   80000           7
d        Diana           HR   60000           2
e          Eve    Marketing   70000           4

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [16]:
df = pd.read_csv("employees.csv")
df.index = ("a","b","c","d","e")
 
df

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [18]:
df.index
df.columns

Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')

In [14]:
df.loc["a":"d", "Department":"Experience":2] # loc is label based indexing

        Department  Experience
index
a      Engineering           3
b        Marketing           5
c      Engineering           7
d               HR           2

In [8]:
import pandas as pd 

print(df.loc[0]) # first row as a series

print(df.loc[0:3])

Name                Alice
Department    Engineering
Salary              75000
Experience              3
Name: 0, dtype: object
      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2

adding & modigying columns

In [27]:
### Adding & modifying columns
df

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [45]:
import pandas as pd

# df["email"] = {}

df["email"] = ["alice@gmail.com",
               "bob@gmail.com",
               "charlies@gmail.com",
               "diana@gmail.com",
               "eve@gmail.com"
]
df

#modify a column
#df["Department"] = "Crime Analytics"
#df

list(df["Department"])

df["Department"] = ['Engineering','Marketing','Physics','HR',
 'Finance']

# use modify all elements in one go
df.Salary = df.Salary / 1000 # scalling operation
# took the column & scaled it down

df.Experience = df.Experience + 1 # experience is increased by 1 year
df

# modifying a value
# df.loc["Department", "d"] = "Crime Analytics"
df.loc["d", "Department"] = "Crime Analytics"
df

ValueError: Length of values (5) does not match length of index (6)

### EDA(Exploratary Data Analysis) with Pandas
- some methods that we can run on dataframes
Basic Inpection methods:
- df.head() - 
- df.tail()
- df.sample()
- df.info()
- df.describe()
- df.shape()
- df.size()
- df.ndim()
- df.types()