### EDA (Exploratory Data Analysis) with Pandas

- first step in data analysis and ML too
- three parts:
    1. Data Cleaning - identify and remove missing values, or outliers etc
    2. Data Summarization - check the dataset characteristics and descriptive statistics
    3. Data Visualization - visualize complex data into visuals for easy interpretation 

- one of the main job responsibiilites of a Data Analyst

- Some methods that we can run on dataframes
- Basic Inspection methods: (Data Summarization)
    - `df.head()` - give you the first 5 elements
        - an argument of 10 will give you first 10 elements
    - df.tail() - last 5 but argument can change the number
    - `df.sample()` - one random entry from the dataset
        - an argument can change that number too 
        - we use this to check how our datasets look like inside
- Basic attributes of a dataframe:
    - `df.shape` - tells you the shape of the df --- how many elements along how many axes
    - df.size - how many elements there are
    - df.ndim - will tell you the number of axes there are in the df --- generally just 2
    - `df.dtypes` - will tell you the data type of each column



- Methods for Statistical information as well:
    - `df.info()` - general information about the df
        - how many records, how many columns, what is the data type of those columns
        - also gives an idea of if there are any missing values in data
    - `df.describe()` - gives us the statistical measurements of the columns like count, mean, min, max, std, percentiles 
-

In [2]:
import pandas as pd

df = pd.read_csv("wc_2026.csv")
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [28]:
df.head()
df.tail()
df.sample(5)

df.shape
df.size 
df.dtypes

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     object
 1   stage                104 non-null    object
 2   team1                104 non-null    object
 3   team2                104 non-null    object
 4   venue                104 non-null    object
 5   city                 104 non-null    object
 6   country              104 non-null    object
 7   date                 104 non-null    object
 8   kickoff_et           104 non-null    object
 9   team1_confederation  72 non-null     object
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     object
 12  team2_confederation  72 non-null     object
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     object
dtypes: float64(2), object(13)
memory usage: 12.3+ KB

- object is used for mixed data type
    - same as numpy array if you mixed data types
    -

Exercise:
- Please go to Kaggle
- Download this dataset: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially the EDA that we learnt about in today's class on it

## Filtering
- filter rows and columns
- uses boolean indexing
- keep only the rows you care about
- 
- df[condition] # or mask

In [29]:
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

### Exercise - Pandas Filtering
-

In [44]:
import pandas as pd

df = pd.read_csv("wc_2026.csv")
df.head()


# Question 1: show me the matches played in Canada
mask = df["country"] == 'Canada'
df[mask]


df[df['country'] == 'Canada']


# Question 2: Give me the data for the matches in which team1_fifa_rank was <= 10 
df[df['team1_fifa_rank'] <= 10]

# Question 3: Give me the data for the matches in which both teams were < 10 fifa rank
df[(df['team1_fifa_rank'] < 10) & (df['team2_fifa_rank'] < 10)]
 

# Question 4: Find all matches where Mexico is playing, 
# specifically as team1, AND the venue is "Estadio Azteca"
df[(df["team1"] == "Mexico") & (df["venue"] == "Estadio Azteca")]

# Question 5: Write the code to find all matches played in either "Toronto" OR "Vancouver"
df[(df["city"] == "Toronto") | (df["city"] == "Vancouver")].shape



# Question 6: Write a single line of pandas code to find matches where:
# team1 is ranked strictly better (lower number) than team2 AND
# The match is either in Mexico OR Canada
df[(df["team1_fifa_rank"] < df["team2_fifa_rank"]) & ((df["country"] == "Mexico") | (df["country"] == "Canada"))]


team1_better = df['team1_fifa_rank'] < df['team2_fifa_rank']
match_mex_can = (df['country'] == "Mexico") | (df['country'] == "Canada")
df[team1_better & match_mex_can]

df[(
    df["team1_fifa_rank"] < df["team2_fifa_rank"]) &
    (
        (df["country"] == "Mexico") | (df["country"] == "Canada")
    )]


# only getting the teams and country
mask = (df["team1_fifa_rank"] < df["team2_fifa_rank"]) & ((df["country"] == "Mexico") | (df["country"] == "Canada"))

mask

# mask - True Rows -
# using .loc to target the exact part of the data
df2 = df.loc[mask, ['team1','team2', 'country'] ]
df2

          team1                   team2 country
0        Mexico            South Africa  Mexico
1   South Korea                 Czechia  Mexico
3       Czechia            South Africa  Mexico
6        Canada  Bosnia and Herzegovina  Canada
8   Switzerland  Bosnia and Herzegovina  Canada
9        Canada                   Qatar  Canada
10  Switzerland                  Canada  Canada
31       Sweden                 Tunisia  Mexico
44        Spain            Saudi Arabia  Mexico
69      Croatia                  Panama  Canada

### Sorting Data in DFs
- highest numbers, or alphabetical order
- 
- df.sort_values(by = 'column') -  will sort based on column values
- df.sort_index() - will sort rows based on index
- pass an argument `ascending = False` for decending order

In [48]:
# Sorting data in data frames
df3 = df2.sort_values(by = 'team1', ascending = False)


# what if we did changes to our dataset, and now indicies are all mixed up
df3.sort_index()

          team1                   team2 country
0        Mexico            South Africa  Mexico
1   South Korea                 Czechia  Mexico
3       Czechia            South Africa  Mexico
6        Canada  Bosnia and Herzegovina  Canada
8   Switzerland  Bosnia and Herzegovina  Canada
9        Canada                   Qatar  Canada
10  Switzerland                  Canada  Canada
31       Sweden                 Tunisia  Mexico
44        Spain            Saudi Arabia  Mexico
69      Croatia                  Panama  Canada

## Aggregation
- Sometimes we need to get aggregate values of columns
- methods: sum(), min(), max(), mean()
- 
- AXIS --- 0 >>>>> Column Wise
- AXIS --- 1 >>>>> Row Wise

Use of axis argument 3 places:
- `Aggregate` --- Numpy 2D array --- DataFrame
    - axis = 0 ---> Column wise aggregates
    - axis = 1 ---> Row wise aggregates
    
- `Drop` a column or row in dataframes
    - axis = 0 ---> # Drop ROW
    - axis = 1 ---> # Drop COLUMN

- `Series.agg`(['mean','max','min', 'count', 'sum', 'std', 'var','prod'])

In [97]:
df_emp = pd.read_csv('employee.csv')
df_emp

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [96]:
df_emp[['Salary','Experience']].mean(axis = 0) # axis = 0  Column wise

df_emp[['Salary','Experience']].mean(axis = 1) # ROW WISE aggregates

0    37501.5
1    32502.5
2    40003.5
3    30001.0
4    35002.0
dtype: float64

In [101]:
# data cleaning
# drop dropna

# targetting the first ROW header, and finding the Column name there
df_emp.drop('Name', axis = 1) #  Drop COLUMN
df_emp.drop(0, axis = 0) # Drop ROW

      Name   Department  Salary  Experience
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [110]:
# Drop all missing values
# Row with a single NaN value --- is dropped
# df.dropna(inplace = True) # Original will be affected

# df.info()

# give me an aggregate for the two columns
df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 0)

# give me an aggregate for the all the 72 rows
df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 1)

0     15.0
1     25.0
2     15.0
3     41.0
4     15.0
      ...
67    53.0
68     4.0
69    11.0
70     4.0
71    11.0
Length: 72, dtype: float64

In [113]:
df['team2_fifa_rank'].agg(['mean','min','max', 'count', 'std', 'var', 'prod'])

mean      3.791667e+01
min       1.000000e+00
max       9.500000e+01
count     7.200000e+01
std       2.383674e+01
var       5.681901e+02
prod     1.317922e+104
Name: team2_fifa_rank, dtype: float64

## Grouping
- group the data by some category
- `df.groupby('Category')['col1, col2, col3, ...].aggregation()`
- 
- using df.groupy('category').count() - will give you all the columns for each row
- using df.groupy('category').szie() - will give you only the categories and their count
-

In [114]:
df_emp.head()

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [124]:
df_emp.groupby('Department')[['Salary', 'Experience']].mean()

              Salary  Experience
Department
Engineering  77500.0         5.0
HR           60000.0         2.0
Marketing    67500.0         4.5

In [127]:
df

# how many appearances has Mexico made
df.groupby("country").size()

country
Canada     7
Mexico    12
USA       53
dtype: int64

### Combine DataFrames
- two dataframe and you want to combine them together
-

JOINS - 
- are used to combine two tables
- this happens along a KEY column ---> PRIMARY KEY --- we cover this in SQL
- 
- ![](https://tse4.mm.bing.net/th/id/OIP.lRkZ1jamrvFYbSdGu3nF5gAAAA?w=350&h=350&rs=1&pid=ImgDetMain&o=7&rm=3)

In [136]:
# Student info
students = {
    "StudentID": [1, 2, 3],
    "Student": ["Aman", "Sara", "John"]
}
df_students = pd.DataFrame(students)
display(df_students)

# Marks info
marks = {
    "StudentID": [2, 3, 4],
    "Math": [85, 90, 78],
    "English": [88, 92, 80]
}
df_marks = pd.DataFrame(marks)
display(df_marks)

   StudentID Student
0          1    Aman
1          2    Sara
2          3    John

   StudentID  Math  English
0          2    85       88
1          3    90       92
2          4    78       80

In [138]:
# Merge
# INNER JOIN 
df_merged_IJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'inner')
# `on` will be a column that is inside both tables, and each row in this column, should be unique 

# All ID elements should match

df_merged_IJ

   StudentID Student  Math  English
0          2    Sara    85       88
1          3    John    90       92

In [139]:
# LEFT JOIN
df_merged_LJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'left')
df_merged_LJ

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara  85.0     88.0
2          3    John  90.0     92.0

In [140]:
# RIGHT JOIN
df_merged_RJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'right')
df_merged_RJ

   StudentID Student  Math  English
0          2    Sara    85       88
1          3    John    90       92
2          4     NaN    78       80

In [144]:
# OUTER JOIN
df_merged_FJ = pd.merge(df_students, df_marks, on = "StudentID", how = 'outer')
df_merged_FJ

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara  85.0     88.0
2          3    John  90.0     92.0
3          4     NaN  78.0     80.0

![](https://bigtechinterviews.com/wp-content/uploads/2024/03/image-7-768x618.png)

In [150]:
# CONCAT
# Put one table next to the other or On top of the other

pd.concat([df_students,df_marks], ignore_index = False)

   StudentID Student  Math  English
0          1    Aman   NaN      NaN
1          2    Sara   NaN      NaN
2          3    John   NaN      NaN
0          2     NaN  85.0     88.0
1          3     NaN  90.0     92.0
2          4     NaN  78.0     80.0

---

- Most companies still have databases that store data in Relational Databases
- using SQL is traditionally efficient, fast and what everybody
- SQL is good for querrying a database 
    - get data from database
- 
- Pandas is based on python - has a lot of library support
    - easier to do ML with
    - analysis and visualise easily
    - has support for huge data
    - 
    - libraries like pySpark or Apache Spark --- tool used for big data analysis
    - 
    -