## Apriori
- algorithm will help you recommend the next item
-

In [1]:
# pip install mlxtend

In [2]:
import pandas as  pd

# encode data in a form Model can understand
from mlxtend.preprocessing import TransactionEncoder

from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
# dataset of transactions

transactions = [
    ['Milk', 'Butter','Bread'],
    ['Milk','Bread'],
    ['Bread', 'Butter', 'Eggs'],
    ['Milk', 'Eggs'],
    ['Bread', 'Butter', 'Juice']
]

In [4]:
# EDA -- 
# Data Cleaning --- > Data transformation
# Algorithms cannot read words - we convert the data into a True False 0 1 table 
te = TransactionEncoder()

te_array = te.fit_transform(transactions) #.transform(transactions) 

# create a dataframe of these encoded transactions along with table header
df_transactions = pd.DataFrame(te_array, columns = te.columns_)
display(df_transactions)

   Bread  Butter   Eggs  Juice   Milk
0   True    True  False  False   True
1   True   False  False  False   True
2   True    True   True  False  False
3  False   False   True  False   True
4   True    True  False   True  False

In [ ]:
# Find frequently bought items

# Run the Apriori
frequent_itemsets = apriori(df_transactions, 
                            min_support = 0.4, # we only care about the items bought in 40 % of transaction
                            use_colnames = True)

In [ ]:
clean_itemsets = frequent_itemsets['itemsets']
#  clean the frozenset output

   support         itemsets
0      0.8          (Bread)
1      0.6         (Butter)
2      0.4           (Eggs)
3      0.6           (Milk)
4      0.6  (Butter, Bread)
5      0.4    (Milk, Bread)

- Support: How often the rule appears in the dataset.
- Confidence: Probability of buying item B if item A is bought.
- Lift: Strength of the rule over random chance. (>1 means it's a good rule)

In [20]:
# generate association rules
# rules to find what is likely going to be bought
rules = association_rules(frequent_itemsets, # dataframe of itemsets and support
                          metric = 'confidence',
                          min_threshold = 0.4, # atleast 70 % confidence
                          )

final_table = rules[['antecedents',	'consequents',	'support',	'confidence','lift']]

display(final_table)

  antecedents consequents  support  confidence      lift
0    (Butter)     (Bread)      0.6    1.000000  1.250000
1     (Bread)    (Butter)      0.6    0.750000  1.250000
2      (Milk)     (Bread)      0.4    0.666667  0.833333
3     (Bread)      (Milk)      0.4    0.500000  0.833333

In [27]:
# test our system

current_cart = {'Bread'} # frozenset({'Bread})

# find consequent based on the antecedant
recommendations = final_table[rules['antecedents'] == current_cart]

recommendations

  antecedents consequents  support  confidence      lift
1     (Bread)    (Butter)      0.6        0.75  1.250000
3     (Bread)      (Milk)      0.4        0.50  0.833333