## Working with DataFrames
-

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("employee.csv")
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

## Column Selection in Pandas
- df["column_name"]
- df.Column_name 
- a single column will exist as a series object
- 
- df[data] - this indexing method will take a single argument --- a `string` or a `list`
    - what if we need multiple columns
    -

In [10]:
# acessing columns in the dataframe
# access columns by --- Name
df['Name']
df.Name # only one column


columns = ["Name","Salary",	"Experience"]
df[columns]

# subset of dataframe
df_salary = df[["Salary",	"Experience"]]
display(df_salary)

#df["Name","Salary"] # will not work

   Salary  Experience
0   75000           3
1   65000           5
2   80000           7
3   60000           2
4   70000           4

In [55]:
display(df)

          Name   Department  Salary  Experience
index
a        Alice  Engineering   75000           3
b          Bob    Marketing   65000           5
c      Charlie  Engineering   80000           7
d        Diana           HR   60000           2
e          Eve    Marketing   70000           4

## Selection using the Location or Labels
##### integer Location --- **.iloc[]**
- `df.iloc[row index]` # access rows
- 
- `df.iloc[row_index_slice]` # [start: end : stepsize]
- INDEXING ----
- `df.iloc[row_slice, column_slice]`
-

In [35]:
df.iloc[0] # first row as a series object

df.iloc[-1] # last row

df.iloc[1:3] # rows from 1 upto 3

df.iloc[1:4:2] # in steps of 2

# ---- indexing works

df.iloc[:4, 1:3] #first 4 rows, 

df.iloc[[0,2,3], [0,2,3]] # you can access the rows, columns by number, but
# if out of index, error will be thrown
# errors are not thrown if you are accessing using slices

      Name  Salary  Experience
0    Alice   75000           3
2  Charlie   80000           7
3    Diana   60000           2

In [37]:
# i want the data of the last two entries, for department and experience
df.iloc[-2:,[1,3]]

  Department  Experience
3         HR           2
4  Marketing           4

#####  Label - .loc[]
- focuses on labels
- df.loc[0:3] # targets the names of these rows
- Which are the indexes
-

In [63]:
# 
ind = ['a','b','c','d','e']
df = pd.read_csv("employee.csv")
df['index'] = ind

df = df.set_index('index')
display(df)
# -----
df.index = ['a','b','c','d','e']
display(df)

          Name   Department  Salary  Experience
index
a        Alice  Engineering   75000           3
b          Bob    Marketing   65000           5
c      Charlie  Engineering   80000           7
d        Diana           HR   60000           2
e          Eve    Marketing   70000           4

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [44]:
df.loc[0] # row
df.loc[0:3] # slice of rows

# df.loc[0:3, 0:3] # throws an error

df.loc[0:3, ['Department', 'Experience']]

    Department  Experience
0  Engineering           3
1    Marketing           5
2  Engineering           7
3           HR           2

In [59]:
df.loc['a':'d', 'Department':'Experience':2]

        Department  Experience
index
a      Engineering           3
b        Marketing           5
c      Engineering           7
d               HR           2

In [ ]:
df = pd.read_csv("employee.csv")

df.index = ("a","b","c","d","e")
 
df

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [62]:
df.index
df.columns

Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')

### Adding and Modifying Columns
-