In [13]:
#pip install pandas

# DataFrames from Files
 
# From a CSV file
#df_csv = pd.read_csv('my_data.csv')
 
# From an Excel file
#df_excel = pd.read_excel('my_data.xlsx')
 
# From a JSON file or API response
#df_json = pd.read_json('my_data.json')

In [4]:
import pandas as pd

maths = pd.Series([20, 30, 40], dtype='int8', name = 'Maths')
type(maths)

print(maths)

0    20
1    30
2    40
Name: Maths, dtype: int8

In [5]:
english = pd.Series([20,30,40])
python = pd.Series([20,30,40])
science = pd.Series([20,30,40])

In [ ]:
pd.concat([maths, english, python, science], axis=1)

   Maths   0   1   2
0     20  20  20  20
1     30  30  30  30
2     40  40  40  40

In [8]:
data = {
    "Students": ["Ali", "Ahmad", "Amin"],
    "Maths": [85, 95, 90],
    "English": [80, 90, 85],
    "Python": [90, 85, 95],
    "Science": [88, 92, 91]
}
df = pd.DataFrame(data)
print(df)
display(df)

  Students  Maths  English  Python  Science
0      Ali     85       80      90       88
1    Ahmad     95       90      85       92
2     Amin     90       85      95       91

  Students  Maths  English  Python  Science
0      Ali     85       80      90       88
1    Ahmad     95       90      85       92
2     Amin     90       85      95       91

In [10]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Paris'}
]
 
df = pd.DataFrame(data)
print(df)
display(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [18]:
temperatures = pd.Series([30, 25, 28, 32, 27], dtype='int8', name='Temperature')
type(temperatures)

print("Series: Temperatures")
print(temperatures)

print("\nType of Series:")
print(type(temperatures))

Series: Temperatures
0    30
1    25
2    28
3    32
4    27
Name: Temperature, dtype: int8

Type of Series:
<class 'pandas.Series'>

In [19]:
data = {
    "City": ["New York", "London", "Paris"],
    "Temperature": [30, 25, 28]
}

df = pd.DataFrame(data)
display(df)

print("\nType of DataFrame:")
print(type(df))

       City  Temperature
0  New York           30
1    London           25
2     Paris           28

Type of DataFrame:
<class 'pandas.DataFrame'>

In [20]:
temperatures = pd.Series([30, 25, 28, 32, 27], dtype='int8', name='Temperature')
type(temperatures)

print("Series: Temperatures")
print(temperatures)

print("\nType of Series:")
print(type(temperatures))

data = {
    "City": ["New York", "London", "Paris"],
    "Temperature": [30, 25, 28]
}

df = pd.DataFrame(data)
display(df)

print("\nType of DataFrame:")
print(type(df))

Series: Temperatures
0    30
1    25
2    28
3    32
4    27
Name: Temperature, dtype: int8

Type of Series:
<class 'pandas.Series'>

       City  Temperature
0  New York           30
1    London           25
2     Paris           28

Type of DataFrame:
<class 'pandas.DataFrame'>

In [6]:
import pandas as pd

sample_data = """Name,Department,Salary,Experience
Alice,HR,50000,5
Bob,Engineering,70000,7
Charlie,Marketing,60000,6
David,Engineering,75000,8
Eve,HR,52000,4"""

with open('fatiniemployees.csv', 'w') as f:
    f.write(sample_data)

In [7]:
df = pd.read_csv('fatiniemployees.csv')
display(df)

      Name   Department  Salary  Experience
0    Alice           HR   50000           5
1      Bob  Engineering   70000           7
2  Charlie    Marketing   60000           6
3    David  Engineering   75000           8
4      Eve           HR   52000           4

In [8]:
import pandas as pd

df = pd.read_csv('fatiniemployees.csv')
display(df)

      Name   Department  Salary  Experience
0    Alice           HR   50000           5
1      Bob  Engineering   70000           7
2  Charlie    Marketing   60000           6
3    David  Engineering   75000           8
4      Eve           HR   52000           4

In [ ]:
df.iloc[-2:, [1, 3]]

    Department  Experience
3  Engineering           8
4           HR           4

In [20]:
df = pd.read_csv('fatiniemployees.csv')
df.index = ['a', 'b', 'c', 'd', 'e']
display(df)

      Name   Department  Salary  Experience
a    Alice           HR   50000           5
b      Bob  Engineering   70000           7
c  Charlie    Marketing   60000           6
d    David  Engineering   75000           8
e      Eve           HR   52000           4